Regression Task:

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/drive/MyDrive/AI_sem-3/diabetes.csv")

Predict the Blood Pressure of the patients based on other features.

In [2]:
#displaying information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [3]:
#Checking if there are any missing values
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Use Linear Regression model from Scikit-learn.

In [10]:
# dropping the target column
features=df.drop("BloodPressure",axis=1)

# selecting only the target column
target=df["BloodPressure"]

In [11]:
# feature matrix
X=np.array(features)
print(X.shape)

(768, 8)


In [12]:
# target vector
y=np.array(target)
print(y.shape)

(768,)


In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [14]:
# splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
# printing shapes
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(614, 8)
(154, 8)
(614,)
(154,)


In [16]:
# initializing the scaler and scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
#initializing the regression model
regression_model=LinearRegression()

# training the regression model
regression_model.fit(X_train_scaled,y_train)

LinearRegression()

In [18]:
# making predictions uisng test data
y_pred=regression_model.predict(X_test_scaled)
print(y_pred)

[76.73337586 69.90169239 61.19862988 64.04439662 74.77414338 83.4470734
 56.99274    71.63327722 75.63220031 82.85778327 69.59472685 89.28803491
 66.39097112 73.82574022 63.8017783  68.18222856 71.86582779 66.15642506
 66.54914618 69.66539695 71.17757085 68.56440836 85.62079721 66.07452712
 78.15451581 78.81508325 66.5732718  59.7426553  70.849067   69.18239603
 82.3082984  81.4364907  74.78548873 64.17623674 79.89778863 72.5631288
 98.93510656 69.61112735 81.03974981 66.04201673 65.30890975 76.58255406
 84.52654248 65.54867835 58.34110819 68.56960524 81.77115164 72.89526269
 73.32504109 91.36245483 61.86928762 78.18506035 85.76649107 58.2378346
 60.48740844 64.58970495 80.80506628 44.87565588 72.13652556 70.05967319
 77.0260046  72.39537599 72.51252868 65.03936629 69.00944125 80.38791571
 63.72880849 74.44501485 56.67080029 75.15001857 80.78378677 67.9818652
 72.78972316 64.76934801 61.54562928 89.8878845  69.78634522 70.27197469
 66.51008697 68.58476061 66.58662534 64.66131017 67.575

In [19]:
# calculating mean squared error
mse = mean_squared_error(y_test,y_pred)
print(f"Mean Squared Error:{mse:.3f}")

Mean Squared Error:402.852


In [20]:
# calculating r2 score
r2 = r2_score(y_test,y_pred)
print(f"R-squared Score:{r2:.3f}")

R-squared Score:0.194


In [21]:
# calculating mean absolute error
mae = mean_absolute_error(y_test,y_pred)
print(f"Mean Absolute Error:{mae:.3f}")

Mean Absolute Error:12.600


Classification Task:

Predict whether the patient has diabetes (target column: Outcome).

In [22]:
# dropping the target column
feature_classification = df.drop("Outcome", axis=1)

# selecting only the target column
target_classification = df["Outcome"]

In [23]:
# feature matrix for classification task
X_1 = np.array(feature_classification)
print(X.shape)

(768, 8)


In [24]:
# target vector for classification task
y_1 = np.array(target_classification)
print(y.shape)

(768,)


In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

In [26]:
# splitting data into train and test sets
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.2, random_state=42)

In [27]:
#printing shapes
print(X_train_1.shape)
print(X_test_1.shape)
print(y_train_1.shape)
print(y_test_1.shape)

(614, 8)
(154, 8)
(614,)
(154,)


In [28]:
# Initializing the scaler and scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_1)
X_test_scaled = scaler.transform(X_test_1)
print(X_train_scaled)

[[-0.52639686 -1.15139792 -3.75268255 ... -4.13525578 -0.49073479
  -1.03594038]
 [ 1.58804586 -0.27664283  0.68034485 ... -0.48916881  2.41502991
   1.48710085]
 [-0.82846011  0.56687102 -1.2658623  ... -0.42452187  0.54916055
  -0.94893896]
 ...
 [ 1.8901091  -0.62029661  0.89659009 ...  1.76054443  1.981245
   0.44308379]
 [-1.13052335  0.62935353 -3.75268255 ...  1.34680407 -0.78487662
  -0.33992901]
 [-1.13052335  0.12949347  1.43720319 ... -1.22614383 -0.61552223
  -1.03594038]]


In [30]:
# initialize the classification model
classification_model = LogisticRegression()

# training the model
classification_model.fit(X_train_scaled, y_train)

LogisticRegression()

In [31]:
# making predictions using test data
y_pred = classification_model.predict(X_test_scaled)
print(y_pred)

[60 70 62 72 80 80 62  0 74 78 72 90 70 80 64 64 78 70  0 64 74 80 78 64
 70 90 62 74 80 80 78 76 90  0 82 70 78 80 72  0 62 60 78 62 96 70 82 78
 72 82 62 84 84 70 64 68 74  0 64 70 78 70 82 62 80 90 62 90 74 64 70 80
 72 80 62 88 80 60 64 80 70 64 60 90 64 70 78 68 74 60 64 76  0  0 60 78
 62 68 64 80 90 80 84 70 76 90 64 74 80 78 64 96  0 90 70 64 64 70 62  0
 62 68 74 64 64 78  0 72  0 90 70 70 64 74 64 74 96 90 74 62 64 62 74 64
 52 78 72 62 78 84 64 76 70 68]


In [32]:
# calculating accuracy
acc_score = accuracy_score(y_test_1, y_pred)
print(f"Accuracy Score: {acc_score:.3f}")

Accuracy Score: 0.032


In [33]:
# displaying confusion matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[11  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
