In [ ]:
import numpy as np

# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")


0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



4.1.1

In [ ]:
#problem 1. Array Creation:
import numpy as np
#empty array with size 2*2
empty_arr= np.empty((2,2))
print("1. empty array with size 2*2: ",empty_arr)

ones_array= np.ones((4,2))
print("2. all one array with size 4*2: ",ones_array)

fill_value= np.full((3,3),7)
print("3. new array of given shape and type: ",fill_value)

given_array= np.array([[1,2,3],[3,4,5]])
zeros_like_array=np.zeros_like(given_array)
print("4. new arrays of zeros as same shape as a given array: ", zeros_like_array)

zeros_like_array=np.ones_like(given_array)
print("5. new array of ones as the same shape as given array: ",zeros_like_array)

new_list=[1,2,3,4]
numpy_array= np.array(new_list)
print("6. List converted to numpy:", numpy_array)


1. empty array with size 2*2:  [[4.88374521e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
2. all one array with size 4*2:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3. new array of given shape and type:  [[7 7 7]
 [7 7 7]
 [7 7 7]]
4. new arrays of zeros as same shape as a given array:  [[0 0 0]
 [0 0 0]]
5. new array of ones as the same shape as given array:  [[1 1 1]
 [1 1 1]]
6. NumPy array from the list: [1 2 3 4]


In [ ]:
#problem 2. Array Manipulation: Numerical Ranges and Array indexing:
import numpy as np

array_range=np.arange(10,50)
print("1. an array with values from 10 to 49:", array_range)

matrix_range=np.arange(9).reshape((3,3))
print("2. 3*3 matrix with value ranging from 0 to 8:",matrix_range)

identity_matirx=np.eye(3)
print("3. identity matrix:",identity_matirx)

random_array= np.random.random(30)
mean_value= random_array.mean()
print("4. random array of size 30:",random_array)
print("mean of the array:",mean_value)

random_10=np.random.random((10,10))
min_value= random_10.min()
max_value= random_10.max()
print("5. 10*10 array with random value:",random_10)
print("minimum value:",min_value)
print("maximum value:",max_value)

zero_array=np.zeros(10)
zero_array[4]=1
print("Array after editing: \n", zero_array)

sample_array = [1,2,0,0,4,0]
print("Sample Array: \n",sample_array)
print("Fliped Array: \n",np.flip(sample_array))

array = np.zeros((6, 6))
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print("Array with 1 in all border: \n",array)

array = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
      if ((i+ j) % 2 == 0):
          array[i][j] = 1


print("Array with checkboard pattern: \n",array)

1. an array with values from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 3*3 matrix with value ranging from 0 to 8: [[0 1 2]
 [3 4 5]
 [6 7 8]]
3. identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. random array of size 30: [0.82148402 0.07393629 0.33476134 0.8129496  0.49689723 0.59375227
 0.88577902 0.96359663 0.22259103 0.68698954 0.41931882 0.31035816
 0.17403098 0.75642499 0.42491681 0.44339252 0.83264217 0.44330306
 0.09376649 0.72322903 0.12928511 0.83150701 0.74265491 0.42888711
 0.22692464 0.48349339 0.81418316 0.44308521 0.0220451  0.74733288]
mean of the array: 0.512783950607801
5. 10*10 array with random value: [[0.76310889 0.74834342 0.41915578 0.13613133 0.6729094  0.56874891
  0.84317157 0.95997047 0.79053933 0.37743011]
 [0.20879058 0.07756909 0.5747542  0.99019388 0.3845771  0.96209271
  0.25591486 0.79879691 0.13352033 0.95857705]
 [0.91753074 0.32337839 0.5337435  0.97177

In [ ]:
# Problem 3

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The result of sum of array x and y is: \n",np.add(x, y))
print("The result of sum of array v and w is: \n",np.add(v, w))

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The result of subtraction of array x and y is: \n",np.subtract(x, y))
print("The result of subtraction of array v and w is: \n",np.subtract(v, w))

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The result of multiplication of array x with 2 is: \n",np.multiply(x, 2))
print("The result of multiplication of array y with 2 is: \n",np.multiply(y, 2))
print("The result of multiplication of array v with 2 is: \n",np.multiply(v, 2))
print("The result of multiplication of array w with 2 is: \n",np.multiply(w, 2))

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The result of square of array x is: \n",np.square(x))
print("The result of square of array y is: \n",np.square(y))
print("The result of square of array v is: \n",np.square(v))
print("The result of square of array w is: \n",np.square(w))

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The result of dot product of array v and w is: \n",np.dot(v,w))
print("The result of dot product of array x and v is: \n",np.dot(x,v))
print("The result of dot product of array x and y is: \n",np.dot(x,y))

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The result of concatenation of array x and y in row is: \n",np.concatenate((x, y),axis=0))
print("The result of concatenation of array v and w in column is: \n",np.vstack((v, w)))

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The result of concatenation of array x and v in row is: \n",np.concatenate((x, v),axis=0))
#The error is due to the difference of dimesion where x is 2,2 while b is 1,2.

#problem 4 (Matrix operation)
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#proves: A * inverse(A) = I
print(np.dot(A,np.linalg.inv(A)))

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
print("A.B: \n",np.dot(A,B), "\nB.A: \n",np.dot(B,A))
print("Hence proves AB ̸= BA.")

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
print(np.transpose(np.dot(A,B)))
print(np.dot(np.transpose(B),np.transpose(A)))
print("Hence proves (AB)T = BTAT.")

A = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B = np.reshape(np.array([-1,-3,9]),(3,1))
A_inverse = np.linalg.inv(A)
answer = np.dot(A_inverse,B)
print("Answer: \n", answer)

The result of sum of array x and y is: 
 [[ 6  8]
 [10 13]]
The result of sum of array v and w is: 
 [20 22]
The result of subtraction of array x and y is: 
 [[-4 -4]
 [-4 -3]]
The result of subtraction of array v and w is: 
 [-2 -2]
The result of multiplication of array x with 2 is: 
 [[ 2  4]
 [ 6 10]]
The result of multiplication of array y with 2 is: 
 [[10 12]
 [14 16]]
The result of multiplication of array v with 2 is: 
 [18 20]
The result of multiplication of array w with 2 is: 
 [22 24]
The result of square of array x is: 
 [[ 1  4]
 [ 9 25]]
The result of square of array y is: 
 [[25 36]
 [49 64]]
The result of square of array v is: 
 [ 81 100]
The result of square of array w is: 
 [121 144]
The result of dot product of array v and w is: 
 219
The result of dot product of array x and v is: 
 [29 77]
The result of dot product of array x and y is: 
 [[19 22]
 [50 58]]
The result of concatenation of array x and y in row is: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
The result of concatenati

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#4.2 Experiment: How Fast is Numpy?
#1. Element-wise Addition:
import time
import numpy as np

#define the size of the arrays/lists
size = 1_000_000

#create two Python lists with 1,000,000 elements
list1 = list(range(size))
list2 = list(range(size))

#measure the time taken for element-wise addition using Python lists
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for addition using Python lists: {python_time:.6f} seconds")

# Create two NumPy arrays with 1,000,000 elements
array1 = np.arange(size)
array2 = np.arange(size)

#measure the time taken for element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for addition using NumPy arrays: {numpy_time:.6f} seconds")

#performance comparison
print(f"NumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists.")


Time taken for addition using Python lists: 0.169538 seconds
Time taken for addition using NumPy arrays: 0.005909 seconds
NumPy is approximately 28.69 times faster than Python lists.


In [ ]:
#2. Element-wise Multiplication
import time
import numpy as np

#define the size of the arrays/lists
size = 1_000_000

#create two Python lists with 1,000,000 elements
list1 = list(range(size))
list2 = list(range(size))

#measure the time taken for element-wise multiplication using Python lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for multiplication using Python lists: {python_time:.6f} seconds")

#create two NumPy arrays with 1,000,000 elements
array1 = np.arange(size)
array2 = np.arange(size)

#measure the time taken for element-wise multiplication using NumPy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for multiplication using NumPy arrays: {numpy_time:.6f} seconds")

#performance comparison
print(f"NumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists.")

Time taken for multiplication using Python lists: 0.273374 seconds
Time taken for multiplication using NumPy arrays: 0.006192 seconds
NumPy is approximately 44.15 times faster than Python lists.


In [ ]:
# 3. Dot Product
import time
import numpy as np

#define the size of the arrays/lists
size = 1_000_000

#create two Python lists with 1,000,000 elements
list1 = list(range(size))
list2 = list(range(size))

#measure the time taken to compute the dot product using Python lists
start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(size)])
end_time = time.time()
python_time = end_time - start_time
print(f"Dot product using Python lists: {dot_product_list}")
print(f"Time taken for dot product using Python lists: {python_time:.6f} seconds")

#create two NumPy arrays with 1,000,000 elements
array1 = np.arange(size)
array2 = np.arange(size)

#measure the time taken to compute the dot product using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"Dot product using NumPy arrays: {dot_product_array}")
print(f"Time taken for dot product using NumPy arrays: {numpy_time:.6f} seconds")

#performance comparison
print(f"NumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists.")

Dot product using Python lists: 333332833333500000
Time taken for dot product using Python lists: 0.202627 seconds
Dot product using NumPy arrays: 333332833333500000
Time taken for dot product using NumPy arrays: 0.001508 seconds
NumPy is approximately 134.41 times faster than Python lists.


In [ ]:
# 4. Matrix Multiplication
import time
import numpy as np

#define the size of the matrices
size = 1000

#create two 1000x1000 matrices using Python lists
matrix1 = [[i + j for j in range(size)] for i in range(size)]
matrix2 = [[i * j for j in range(size)] for i in range(size)]

#measure time for matrix multiplication using Python lists
start_time = time.time()

#initialize the result matrix
result_list = [[0] * size for _ in range(size)]

#perform matrix multiplication
for i in range(size):
    for j in range(size):
        for k in range(size):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for matrix multiplication using Python lists: {python_time:.6f} seconds")

#create two 1000x1000 matrices using NumPy arrays
array1 = np.arange(size * size).reshape(size, size)
array2 = np.arange(size * size).reshape(size, size)

#measure time for matrix multiplication using NumPy
start_time = time.time()
result_array = np.dot(array1, array2)  # or array1 @ array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for matrix multiplication using NumPy: {numpy_time:.6f} seconds")

#performance comparison
print(f"NumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists.")

Time taken for matrix multiplication using Python lists: 482.040996 seconds
Time taken for matrix multiplication using NumPy: 1.819175 seconds
NumPy is approximately 264.98 times faster than Python lists.
